name: Run tests

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Generate required .env file
        run: |
          echo DEBUG=True >> .env
          echo FLASK_DEBUG=1 >> .env
          echo FLASK_APP=run.py >> .env
      - name: Building containers
        run: docker-compose build
      - name: Run tests
        run: docker-compose up --abort-on-container-exit test-runner
      